## Collect the Data

In [1]:
import requests
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import unicodedata
import sys

In [20]:
#define helper functions

def date_time(table_cells):
    """
    This function returns the data and time from the HTML  table cell
    Input: the  element of a table data cell extracts extra row
    """
    return [data_time.strip() for data_time in list(table_cells.strings)][0:2]

def booster_version(table_cells):
    """
    This function returns the booster version from the HTML  table cell 
    Input: the  element of a table data cell extracts extra row
    """
    out=''.join([booster_version for i,booster_version in enumerate( table_cells.strings) if i%2==0][0:-1])
    return out

def landing_status(table_cells):
    """
    This function returns the landing status from the HTML table cell 
    Input: the  element of a table data cell extracts extra row
    """
    out=[i for i in table_cells.strings][0]
    return out


def get_mass(table_cells):
    mass=unicodedata.normalize("NFKD", table_cells.text).strip()
    if mass:
        mass.find("kg")
        new_mass=mass[0:mass.find("kg")+2]
    else:
        new_mass=0
    return new_mass


def extract_column_from_header(row):
    """
    This function returns the landing status from the HTML table cell 
    Input: the  element of a table data cell extracts extra row
    """
    if (row.br):
        row.br.extract()
    if row.a:
        row.a.extract()
    if row.sup:
        row.sup.extract()
        
    colunm_name = ' '.join(row.stripped_strings)
    
    # Filter the digit and empty names
    if not(colunm_name.strip().isdigit()):
        colunm_name = colunm_name.strip()
        return colunm_name

In [5]:
static_url = "https://en.wikipedia.org/w/index.php?title=List_of_Falcon_9_and_Falcon_Heavy_launches&oldid=1027686922"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/91.0.4472.124 Safari/537.36"
}

In [10]:
response = requests.get(static_url, headers=headers)
content = response.content
print(response.status_code)

200

In [15]:
soup = BeautifulSoup(response.content, "html.parser")
print(soup.title)

<title>List of Falcon 9 and Falcon Heavy launches - Wikipedia</title>

In [16]:
html_tables = soup.find_all('table')
first_launch_table = html_tables[2]
print(first_launch_table)

<table class="wikitable plainrowheaders collapsible" id="mwmQ" style="width: 100%;">
<tbody id="mwmg"><tr id="mwmw"><th id="mwnA" scope="col">Flight No.</th>
<th id="mwnQ" scope="col">Date and<br id="mwng"/>time (<a href="https://en.wikipedia.org/wiki/Coordinated_Universal_Time" id="mwnw" rel="mw:WikiLink" title="Coordinated Universal Time">UTC</a>)</th>
<th id="mwoA" scope="col"><a href="https://en.wikipedia.org/wiki/List_of_Falcon_9_first-stage_boosters" id="mwoQ" rel="mw:WikiLink" title="List of Falcon 9 first-stage boosters">Version,<br id="mwog"/>Booster</a> <sup about="#mwt70" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"booster","group":"lower-alpha"},"body":{"id":"mw-reference-text-cite_note-booster-11"},"parts":[{"template":{"target":{"wt":"efn","href":"./Template:Efn"},"params":{"name":{"wt":"booster"},"1":{"wt":"Falcon 9 first-stage boosters are designated with a construction serial number and an optional flight number when reused, e.g. B1021.1 and B1021.2 represent the two flights of booster [[B1021]]. Launches using reused boosters are denoted with a recycled symbol ♺."}},"i":0}}]}' id="cite_ref-booster_11-0" rel="dc:references" typeof="mw:Transclusion mw:Extension/ref"><a data-mw-group="lower-alpha" href="#cite_note-booster-11" id="mwow"><span class="mw-reflink-text" id="mwpA"><span class="cite-bracket" id="mwpQ">[</span>b<span class="cite-bracket" id="mwpg">]</span></span></a></sup></th>
<th id="mwpw" scope="col">Launch site</th>
<th id="mwqA" scope="col">Payload<sup about="#mwt73" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"Dragon","group":"lower-alpha"},"body":{"id":"mw-reference-text-cite_note-Dragon-12"},"parts":[{"template":{"target":{"wt":"efn","href":"./Template:Efn"},"params":{"name":{"wt":"Dragon"},"1":{"wt":"Dragon 1 or 2 are designated with a construction serial number or name and an optional flight number when reused, e.g. Dragon C106.1 and Dragon C106.2 represent the two flights of [[Dragon C106]]. Dragon Spacecrafts that are reused are denoted with a recycled symbol ♺."}},"i":0}}]}' id="cite_ref-Dragon_12-0" rel="dc:references" typeof="mw:Transclusion mw:Extension/ref"><a data-mw-group="lower-alpha" href="#cite_note-Dragon-12" id="mwqQ"><span class="mw-reflink-text" id="mwqg"><span class="cite-bracket" id="mwqw">[</span>c<span class="cite-bracket" id="mwrA">]</span></span></a></sup></th>
<th id="mwrQ" scope="col">Payload mass</th>
<th id="mwrg" scope="col">Orbit</th>
<th id="mwrw" scope="col">Customer</th>
<th id="mwsA" scope="col">Launch<br id="mwsQ"/>outcome</th>
<th id="mwsg" scope="col"><a href="https://en.wikipedia.org/wiki/Falcon_9_first-stage_landing_tests" id="mwsw" rel="mw:WikiLink" title="Falcon 9 first-stage landing tests">Booster<br id="mwtA"/>landing</a></th></tr>
<tr id="mwtQ">
<th id="mwtg" rowspan="2" scope="row" style="text-align:center;">1</th>
<td id="mwtw">4 June 2010,<br id="mwuA"/>18:45</td>
<td id="mwuQ"><a href="https://en.wikipedia.org/wiki/Falcon_9_v1.0" id="mwug" rel="mw:WikiLink" title="Falcon 9 v1.0">F9 v1.0</a><sup about="#mwt78" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"MuskMay2012"},"body":{"id":"mw-reference-text-cite_note-MuskMay2012-13"}}' id="cite_ref-MuskMay2012_13-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-MuskMay2012-13" id="mwuw"><span class="mw-reflink-text" id="mwvA"><span class="cite-bracket" id="mwvQ">[</span>7<span class="cite-bracket" id="mwvg">]</span></span></a></sup><br id="mwvw"/>B0003.1<sup about="#mwt79" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"block_numbers"}}' id="cite_ref-block_numbers_14-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-block_numbers-14" id="mwwA"><span class="mw-reflink-text" id="mwwQ"><span class="cite-bracket" id="mwwg">[</span>8<span class="cite-bracket" id="mwww">]</span></span></a></sup></td>
<td id="mwxA"><a href="https://en.wikipedia.org/wiki/Cape_Canaveral_Space_Force_Station" id="mwxQ" rel="mw:WikiLink" title="Cape Canaveral Space Force Station">CCAFS</a>,<br id="mwxg"/><a href="https://en.wikipedia.org/wiki/Cape_Canaveral_Space_Launch_Complex_40" id="mwxw" rel="mw:WikiLink" title="Cape Canaveral Space Launch Complex 40">SLC-40</a></td>
<td id="mwyA"><a href="https://en.wikipedia.org/wiki/Dragon_Spacecraft_Qualification_Unit" id="mwyQ" rel="mw:WikiLink" title="Dragon Spacecraft Qualification Unit">Dragon Spacecraft Qualification Unit</a></td>
<td id="mwyg"></td>
<td id="mwyw"><a href="https://en.wikipedia.org/wiki/Low_Earth_orbit" id="mwzA" rel="mw:WikiLink" title="Low Earth orbit">LEO</a></td>
<td id="mwzQ"><a href="https://en.wikipedia.org/wiki/SpaceX" id="mwzg" rel="mw:WikiLink" title="SpaceX">SpaceX</a></td>
<td about="#mwt80" class="table-success" data-mw='{"parts":["| ",{"template":{"target":{"wt":"Success","href":"./Template:Success"},"params":{},"i":0}}]}' id="mwzw" style="background: #9EFF9E; color:black; vertical-align: middle; text-align: center; " typeof="mw:Transclusion">Success</td>
<td about="#mwt81" class="table-failure" data-mw='{"parts":["| ",{"template":{"target":{"wt":"Failure","href":"./Template:Failure"},"params":{},"i":0}},"&lt;ref name=\"ns20110930\"&gt;{{cite web|last1=Spencer|first1=Henry|title=Falcon rockets to land on their toes|url=https://www.newscientist.com/blogs/shortsharpscience/2011/09/falcon-rockets-to-land-on-thei.html|archive-url=https://web.archive.org/web/20171216042334/https://www.newscientist.com/blogs/shortsharpscience/2011/09/falcon-rockets-to-land-on-thei.html|url-status=dead|archive-date=December 16, 2017 |publisher=New Scientist|access-date=July 13, 2016|date=September 30, 2011}}&lt;/ref&gt;&lt;ref&gt;{{cite web|url=http://www.spaceflightnow.com/falcon9/001/100603prelaunch/|title=Falcon 9 demo launch will test more than a new rocket|last1=Clark|first1=Stephen|publisher=SpaceFlight Now|access-date=July 13, 2016|date=June 3, 2010}}&lt;/ref&gt;&lt;br/&gt;&lt;small&gt;(parachute)&lt;/small&gt;"]}' id="mw0A" style="background: #FFC7C7; color:black; vertical-align: middle; text-align: center; " typeof="mw:Transclusion">Failure<sup about="#mwt84" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"ns20110930"},"body":{"id":"mw-reference-text-cite_note-ns20110930-15"}}' id="cite_ref-ns20110930_15-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-ns20110930-15" id="mw0Q"><span class="mw-reflink-text" id="mw0g"><span class="cite-bracket" id="mw0w">[</span>9<span class="cite-bracket" id="mw1A">]</span></span></a></sup><sup about="#mwt87" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-16"}}' id="cite_ref-16" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-16" id="mw1Q"><span class="mw-reflink-text" id="mw1g"><span class="cite-bracket" id="mw1w">[</span>10<span class="cite-bracket" id="mw2A">]</span></span></a></sup><br/><small>(parachute)</small></td></tr>
<tr id="mw2Q">
<td colspan="9" id="mw2g">First flight of Falcon 9 v1.0.<sup about="#mwt88" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"sfn20100604"}}' id="cite_ref-sfn20100604_17-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-sfn20100604-17" id="mw2w"><span class="mw-reflink-text" id="mw3A"><span class="cite-bracket" id="mw3Q">[</span>11<span class="cite-bracket" id="mw3g">]</span></span></a></sup> Used a boilerplate version of Dragon capsule which was not designed to separate from the second stage.<small id="mw3w">(<a class="mw-selflink-fragment" href="#First_flight_of_Falcon_9" id="mw4A" rel="mw:WikiLink">more details below</a>)</small> Attempted to recover the first stage by parachuting it into the ocean, but it burned up on reentry, before the parachutes even deployed.<sup about="#mwt91" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"parachute"},"body":{"id":"mw-reference-text-cite_note-parachute-18"}}' id="cite_ref-parachute_18-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-parachute-18" id="mw4Q"><span class="mw-reflink-text" id="mw4g"><span class="cite-bracket" id="mw4w">[</span>12<span class="cite-bracket" id="mw5A">]</span></span></a></sup></td></tr>
<tr id="mw5Q">
<th id="mw5g" rowspan="2" scope="row" style="text-align:center;">2</th>
<td id="mw5w">8 December 2010,<br id="mw6A"/>15:43<sup about="#mwt94" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"spaceflightnow Clark Launch Report"},"body":{"id":"mw-reference-text-cite_note-spaceflightnow_Clark_Launch_Report-19"}}' id="cite_ref-spaceflightnow_Clark_Launch_Report_19-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-spaceflightnow_Clark_Launch_Report-19" id="mw6Q"><span class="mw-reflink-text" id="mw6g"><span class="cite-bracket" id="mw6w">[</span>13<span class="cite-bracket" id="mw7A">]</span></span></a></sup></td>
<td id="mw7Q"><a href="https://en.wikipedia.org/wiki/Falcon_9_v1.0" id="mw7g" rel="mw:WikiLink" title="Falcon 9 v1.0">F9 v1.0</a><sup about="#mwt95" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"MuskMay2012"}}' id="cite_ref-MuskMay2012_13-1" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-MuskMay2012-13" id="mw7w"><span class="mw-reflink-text" id="mw8A"><span class="cite-bracket" id="mw8Q">[</span>7<span class="cite-bracket" id="mw8g">]</span></span></a></sup><br id="mw8w"/>B0004.1<sup about="#mwt96" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"block_numbers"}}' id="cite_ref-block_numbers_14-1" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-block_numbers-14" id="mw9A"><span class="mw-reflink-text" id="mw9Q"><span class="cite-bracket" id="mw9g">[</span>8<span class="cite-bracket" id="mw9w">]</span></span></a></sup></td>
<td id="mw-A"><a href="https://en.wikipedia.org/wiki/Cape_Canaveral_Space_Force_Station" id="mw-Q" rel="mw:WikiLink" title="Cape Canaveral Space Force Station">CCAFS</a>,<br id="mw-g"/><a href="https://en.wikipedia.org/wiki/Cape_Canaveral_Space_Launch_Complex_40" id="mw-w" rel="mw:WikiLink" title="Cape Canaveral Space Launch Complex 40">SLC-40</a></td>
<td id="mw_A"><a href="https://en.wikipedia.org/wiki/SpaceX_Dragon" id="mw_Q" rel="mw:WikiLink" title="SpaceX Dragon">Dragon</a> <a class="mw-redirect" href="https://en.wikipedia.org/wiki/COTS_Demo_Flight_1" id="mw_g" rel="mw:WikiLink" title="COTS Demo Flight 1">demo flight C1</a><br id="mw_w"/>(Dragon C101)</td>
<td id="mwAQA"></td>
<td id="mwAQE"><a href="https://en.wikipedia.org/wiki/Low_Earth_orbit" id="mwAQI" rel="mw:WikiLink" title="Low Earth orbit">LEO</a> (<a href="https://en.wikipedia.org/wiki/International_Space_Station" id="mwAQM" rel="mw:WikiLink" title="International Space Station">ISS</a>)</td>
<td id="mwAQQ"><span about="#mwt97" class="mw-empty-elt" data-mw='{"parts":[{"template":{"target":{"wt":"plainlist","href":"./Template:Plainlist"},"params":{"1":{"wt":"\n* [[NASA]] ([[Commercial Orbital Transportation Services|COTS]])\n* [[National Reconnaissance Office|NRO]]\n"}},"i":0}}]}' id="mwAQU" typeof="mw:Transclusion"><style about="#mwt98" data-mw='{"name":"templatestyles","attrs":{"src":"Plainlist/styles.css"}}' data-mw-deduplicate="TemplateStyles:r1126788409" typeof="mw:Extension/templatestyles">.mw-parser-output .plainlist ol,.mw-parser-output .plainlist ul{line-height:inherit;list-style:none;margin:0;padding:0}.mw-parser-output .plainlist ol li,.mw-parser-output .plainlist ul li{margin-bottom:0}</style></span><div about="#mwt97" class="plainlist" id="mwAQY">
<ul><li><a href="https://en.wikipedia.org/wiki/NASA" rel="mw:WikiLink" title="NASA">NASA</a> (<a href="https://en.wikipedia.org/wiki/Commercial_Orbital_Transportation_Services" rel="mw:WikiLink" title="Commercial Orbital Transportation Services">COTS</a>)</li>
<li><a href="https://en.wikipedia.org/wiki/National_Reconnaissance_Office" rel="mw:WikiLink" title="National Reconnaissance Office">NRO</a></li></ul>
</div></td>
<td about="#mwt99" class="table-success" data-mw='{"parts":["| ",{"template":{"target":{"wt":"Success","href":"./Template:Success"},"params":{},"i":0}},"&lt;ref name=\"ns20110930\"/&gt;"]}' id="mwAQc" style="background: #9EFF9E; color:black; vertical-align: middle; text-align: center; " typeof="mw:Transclusion">Success<sup about="#mwt100" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"ns20110930"}}' id="cite_ref-ns20110930_15-1" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-ns20110930-15" id="mwAQg"><span class="mw-reflink-text" id="mwAQk"><span class="cite-bracket" id="mwAQo">[</span>9<span class="cite-bracket" id="mwAQs">]</span></span></a></sup></td>
<td about="#mwt101" class="table-failure" data-mw='{"parts":["| ",{"template":{"target":{"wt":"Failure","href":"./Template:Failure"},"params":{},"i":0}},"&lt;ref name=\"ns20110930\"/&gt;&lt;ref&gt;{{cite web|author=Matt|title=Preparations for first Falcon 9 launch|url=http://spacefellowship.com/news/art19992/preparations-for-first-falcon-9-launch.html |publisher=Space Fellowship|access-date=July 13, 2016|date=May 7, 2010}}&lt;/ref&gt;&lt;br/&gt;&lt;small&gt;(parachute)&lt;/small&gt;"]}' id="mwAQw" style="background: #FFC7C7; color:black; vertical-align: middle; text-align: center; " typeof="mw:Transclusion">Failure<sup about="#mwt102" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"ns20110930"}}' id="cite_ref-ns20110930_15-2" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-ns20110930-15" id="mwAQ0"><span class="mw-reflink-text" id="mwAQ4"><span class="cite-bracket" id="mwAQ8">[</span>9<span class="cite-bracket" id="mwARA">]</span></span></a></sup><sup about="#mwt105" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-20"}}' id="cite_ref-20" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-20" id="mwARE"><span class="mw-reflink-text" id="mwARI"><span class="cite-bracket" id="mwARM">[</span>14<span class="cite-bracket" id="mwARQ">]</span></span></a></sup><br/><small>(parachute)</small></td></tr>
<tr id="mwARU">
<td colspan="9" id="mwARY">Maiden flight of <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Dragon_capsule" id="mwARc" rel="mw:WikiLink" title="Dragon capsule">Dragon capsule</a>, consisting of over 3 hours of testing thruster maneuvering and reentry.<sup about="#mwt108" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"spaceflightnow Clark unleashing Dragon"},"body":{"id":"mw-reference-text-cite_note-spaceflightnow_Clark_unleashing_Dragon-21"}}' id="cite_ref-spaceflightnow_Clark_unleashing_Dragon_21-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-spaceflightnow_Clark_unleashing_Dragon-21" id="mwARg"><span class="mw-reflink-text" id="mwARk"><span class="cite-bracket" id="mwARo">[</span>15<span class="cite-bracket" id="mwARs">]</span></span></a></sup> Attempted to recover the first stage by parachuting it into the ocean, but it disintegrated upon reentry, before the parachutes were deployed.<sup about="#mwt109" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"parachute"}}' id="cite_ref-parachute_18-1" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-parachute-18" id="mwARw"><span class="mw-reflink-text" id="mwAR0"><span class="cite-bracket" id="mwAR4">[</span>12<span class="cite-bracket" id="mwAR8">]</span></span></a></sup> <small id="mwASA">(<a class="mw-selflink-fragment" href="#COTS_demo_missions" id="mwASE" rel="mw:WikiLink">more details below</a>)</small> It also included two <a href="https://en.wikipedia.org/wiki/CubeSat" id="mwASI" rel="mw:WikiLink" title="CubeSat">CubeSats</a>,<sup about="#mwt112" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"NRO Taps Boeing for Next Batch of CubeSats"},"body":{"id":"mw-reference-text-cite_note-NRO_Taps_Boeing_for_Next_Batch_of_CubeSats-22"}}' id="cite_ref-NRO_Taps_Boeing_for_Next_Batch_of_CubeSats_22-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-NRO_Taps_Boeing_for_Next_Batch_of_CubeSats-22" id="mwASM"><span class="mw-reflink-text" id="mwASQ"><span class="cite-bracket" id="mwASU">[</span>16<span class="cite-bracket" id="mwASY">]</span></span></a></sup> and a wheel of <a href="https://en.wikipedia.org/wiki/Brouère" id="mwASc" rel="mw:WikiLink" title="Brouère">Brouère</a> cheese.</td></tr>
<tr id="mwASg">
<th id="mwASk" rowspan="2" scope="row" style="text-align:center;">3</th>
<td id="mwASo">22 May 2012,<br id="mwASs"/>07:44<sup about="#mwt113" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"BBC new era"}}' id="cite_ref-BBC_new_era_23-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-BBC_new_era-23" id="mwASw"><span class="mw-reflink-text" id="mwAS0"><span class="cite-bracket" id="mwAS4">[</span>17<span class="cite-bracket" id="mwAS8">]</span></span></a></sup></td>
<td id="mwATA"><a href="https://en.wikipedia.org/wiki/Falcon_9_v1.0" id="mwATE" rel="mw:WikiLink" title="Falcon 9 v1.0">F9 v1.0</a><sup about="#mwt114" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"MuskMay2012"}}' id="cite_ref-MuskMay2012_13-2" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-MuskMay2012-13" id="mwATI"><span class="mw-reflink-text" id="mwATM"><span class="cite-bracket" id="mwATQ">[</span>7<span class="cite-bracket" id="mwATU">]</span></span></a></sup><br id="mwATY"/>B0005.1<sup about="#mwt115" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"block_numbers"}}' id="cite_ref-block_numbers_14-2" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-block_numbers-14" id="mwATc"><span class="mw-reflink-text" id="mwATg"><span class="cite-bracket" id="mwATk">[</span>8<span class="cite-bracket" id="mwATo">]</span></span></a></sup></td>
<td id="mwATs"><a href="https://en.wikipedia.org/wiki/Cape_Canaveral_Space_Force_Station" id="mwATw" rel="mw:WikiLink" title="Cape Canaveral Space Force Station">CCAFS</a>,<br id="mwAT0"/><a href="https://en.wikipedia.org/wiki/Cape_Canaveral_Space_Launch_Complex_40" id="mwAT4" rel="mw:WikiLink" title="Cape Canaveral Space Launch Complex 40">SLC-40</a></td>
<td id="mwAT8"><a href="https://en.wikipedia.org/wiki/SpaceX_Dragon" id="mwAUA" rel="mw:WikiLink" title="SpaceX Dragon">Dragon</a> <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Dragon_C2+" id="mwAUE" rel="mw:WikiLink" title="Dragon C2+">demo flight C2+</a><sup about="#mwt118" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"C2"},"body":{"id":"mw-reference-text-cite_note-C2-24"}}' id="cite_ref-C2_24-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-C2-24" id="mwAUI"><span class="mw-reflink-text" id="mwAUM"><span class="cite-bracket" id="mwAUQ">[</span>18<span class="cite-bracket" id="mwAUU">]</span></span></a></sup><br id="mwAUY"/>(Dragon C102)</td>
<td id="mwAUc"><span about="#mwt119" data-mw='{"parts":[{"template":{"target":{"wt":"cvt","href":"./Template:Cvt"},"params":{"1":{"wt":"525"},"2":{"wt":"kg"}},"i":0}}]}' id="mwAUg" typeof="mw:Transclusion">525</span><span about="#mwt119" typeof="mw:Entity"> </span><span about="#mwt119">kg (1,157</span><span about="#mwt119" typeof="mw:Entity"> </span><span about="#mwt119">lb)</span><sup about="#mwt123" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-25"}}' id="cite_ref-25" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-25" id="mwAUk"><span class="mw-reflink-text" id="mwAUo"><span class="cite-bracket" id="mwAUs">[</span>19<span class="cite-bracket" id="mwAUw">]</span></span></a></sup></td>
<td id="mwAU0"><a href="https://en.wikipedia.org/wiki/Low_Earth_orbit" id="mwAU4" rel="mw:WikiLink" title="Low Earth orbit">LEO</a> (<a href="https://en.wikipedia.org/wiki/International_Space_Station" id="mwAU8" rel="mw:WikiLink" title="International Space Station">ISS</a>)</td>

In [22]:
column_names = []
names = first_launch_table.find_all('th')
for table in names:
    name = extract_column_from_header(table)
    if name is not None and len(name) > 0:
        column_names.append(name)

print(column_names)

['Flight No.', 'Date and time ( )', 'Launch site', 'Payload', 'Payload mass', 'Orbit', 'Customer', 'Launch outcome']

In [23]:
launch_dict = dict.fromkeys(column_names)

del launch_dict['Date and time ( )']

launch_dict['Flight No.'] = []
launch_dict['Launch site'] = []
launch_dict['Payload'] = []
launch_dict['Payload mass'] = []
launch_dict['Orbit'] = []
launch_dict['Customer'] = []
launch_dict['Launch outcome'] = []

# Added some new columns
launch_dict['Version Booster']=[]
launch_dict['Booster landing']=[]
launch_dict['Date']=[]
launch_dict['Time']=[]

In [25]:
extracted_row = 0
#Extract each table 
for table_number,table in enumerate(soup.find_all('table',"wikitable plainrowheaders collapsible")):
   # get table row 
    for rows in table.find_all("tr"):
        #check to see if first table heading is as number corresponding to launch a number 
        if rows.th:
            if rows.th.string:
                flight_number=rows.th.string.strip()
                flag=flight_number.isdigit()
        else:
            flag=False
        #get table element 
        row=rows.find_all('td')
        #if it is number save cells in a dictonary 
        if flag:
            extracted_row += 1
            
            launch_dict['Flight No.'].append(flight_number)
            datatimelist=date_time(row[0])
            
            date = datatimelist[0].strip(',')
            launch_dict['Date'].append(date)

            time = datatimelist[1]
            launch_dict['Time'].append(time)
              
            
            bv=booster_version(row[1])
            if not(bv):
                bv=row[1].a.string
            print(bv)
            launch_dict['Version Booster'].append(bv)
            
            
            launch_site = row[2].a.string
            launch_dict['Launch site'].append(launch_site)
            
            
            payload = row[3].a.string
            launch_dict['Payload'].append(payload)
            
            
            payload_mass = get_mass(row[4])
            launch_dict['Payload mass'].append(payload_mass)
            
            
            orbit = row[5].a.string
            launch_dict['Orbit'].append(orbit)
            
        
            customer = row[6].a.string if row[6].a else ''.join(row[6].stripped_strings)
            launch_dict['Customer'].append(customer)

            launch_outcome = list(row[7].strings)[0]
            launch_dict['Launch outcome'].append(launch_outcome)
            
        
            booster_landing = landing_status(row[8])
            launch_dict['Booster landing'].append(booster_landing)

F9 v1.07B0003.1
F9 v1.07B0004.1
F9 v1.07B0005.1
F9 v1.07B0006.1
F9 v1.07B0007.1
F9 v1.17B1003
F9 v1.1
F9 v1.1
F9 v1.1
F9 v1.1
F9 v1.1
F9 v1.1[
F9 v1.1[
F9 v1.1[
F9 v1.1[
F9 v1.1[
F9 v1.1[
F9 v1.1[
F9 v1.1[
F9 FT[
F9 v1.1[
F9 FT[
F9 FT[
F9 FT[
F9 FT[
F9 FT[
F9 FT[
F9 FT[
F9 FT[
F9 FT[
F9 FT[
F9 FT♺[
F9 FT[
F9 FT[
F9 FT[
F9 FTB1029.2
F9 FT[
F9 FT[
F9 B4[
F9 FT[
F9 B4[
F9 B4[
F9 FTB1031.2
F9 B4[
F9 FTB1035.2
F9 FTB1036.2
F9 B4[
F9 FTB1032.2
F9 FTB1038.2
F9 B4[
F9 B4B1041.2
F9 B4B1039.2
F9 B4[
F9 B5311B1046.1
F9 B4B1043.2
F9 B4B1040.2
F9 B4B1045.2
F9 B5
F9 B5349B1048[
F9 B5B1046.2
F9 B5[
F9 B5B1048.2
F9 B5B1047.2
F9 B5B1046.3268
F9 B5[
F9 B5[
F9 B5B1049.2
F9 B5B1048.3
F9 B5[]
F9 B5[
F9 B5B1049.3
F9 B5B1051.2
F9 B5B1056.2
F9 B5B1047.3
F9 B5
F9 B5[
F9 B5B1056.3
F9 B5
F9 B5
F9 B5
F9 B5
F9 B5
F9 B5
F9 B5
F9 B5[
F9 B5
F9 B5
F9 B5
F9 B5B1058.2
F9 B5
F9 B5B1049.6
F9 B5
F9 B5B1060.2
F9 B5B1058.3
F9 B5B1051.6
F9 B5
F9 B5
F9 B5[
F9 B5
F9 B5 ♺[
F9 B5 ♺[
F9 B5 ♺
F9 B5 ♺
F9 B5
F9 B5B1051.8
F9 B5B1058.5
F9 B5 ♺[
F9 B5 ♺
F9 B5 ♺[
F9 B5 ♺[
F9 B5 ♺
F9 B5B1060.6
F9 B5 ♺
F9 B5B1061.2
F9 B5B1060.7
F9 B5B1049.9
F9 B5B1051.10
F9 B5B1058.8
F9 B5B1063.2
F9 B5B1067.1
F9 B5

In [26]:
df= pd.DataFrame({ key:pd.Series(value) for key, value in launch_dict.items() })

In [27]:
df.head()

,Flight No.,Launch site,Payload,Payload mass,Orbit,Customer,Launch outcome,Version Booster,Booster landing,Date,Time
0,1,CCAFS,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,F9 v1.07B0003.1,Failure,4 June 2010,18:45
1,2,CCAFS,Dragon,0,LEO,NASA,Success,F9 v1.07B0004.1,Failure,8 December 2010,15:43
2,3,CCAFS,Dragon,525 kg,LEO,NASA,Success,F9 v1.07B0005.1,No,22 May 2012,07:44
3,4,CCAFS,SpaceX CRS-1,"4,700 kg",LEO,NASA,Success,F9 v1.07B0006.1,No attempt,8 October 2012,00:35
4,5,CCAFS,SpaceX CRS-2,"4,877 kg",LEO,NASA,Success,F9 v1.07B0007.1,No,1 March 2013,15:10

In [ ]:
df.to_csv('spacex_scraped.csv', index=False)

## Data Wrangling

In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv('spacex_scraped.csv')
df.head(10)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857
5,6,2014-01-06,Falcon 9,3325.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1005,-80.577366,28.561857
6,7,2014-04-18,Falcon 9,2296.000000,ISS,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1006,-80.577366,28.561857
7,8,2014-07-14,Falcon 9,1316.000000,LEO,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1007,-80.577366,28.561857
8,9,2014-08-05,Falcon 9,4535.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1008,-80.577366,28.561857
9,10,2014-09-07,Falcon 9,4428.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1011,-80.577366,28.561857

In [7]:
df.isnull().sum()/len(df) * 100

FlightNumber       0.000000
Date               0.000000
BoosterVersion     0.000000
PayloadMass        0.000000
Orbit              0.000000
LaunchSite         0.000000
Outcome            0.000000
Flights            0.000000
GridFins           0.000000
Reused             0.000000
Legs               0.000000
LandingPad        28.888889
Block              0.000000
ReusedCount        0.000000
Serial             0.000000
Longitude          0.000000
Latitude           0.000000
dtype: float64

In [8]:
df.dtypes

FlightNumber        int64
Date               object
BoosterVersion     object
PayloadMass       float64
Orbit              object
LaunchSite         object
Outcome            object
Flights             int64
GridFins             bool
Reused               bool
Legs                 bool
LandingPad         object
Block             float64
ReusedCount         int64
Serial             object
Longitude         float64
Latitude          float64
dtype: object

In [9]:
#calculate the number of launches on each site
df['LaunchSite'].value_counts()

LaunchSite
CCAFS SLC 40    55
KSC LC 39A      22
VAFB SLC 4E     13
Name: count, dtype: int64

In [10]:
#calculate the number of occurence of each orbit
df['Orbit'].value_counts()

Orbit
GTO      27
ISS      21
VLEO     14
PO        9
LEO       7
SSO       5
MEO       3
HEO       1
ES-L1     1
SO        1
GEO       1
Name: count, dtype: int64

In [22]:
# calculate the number and occurence of mission outcome of the orbits
landing_outcomes = df['Outcome'].value_counts()
landing_outcomes

Outcome
True ASDS      41
None None      19
True RTLS      14
False ASDS      6
True Ocean      5
False Ocean     2
None ASDS       2
False RTLS      1
Name: count, dtype: int64

`True Ocean` means the mission outcome was successfully  landed to a specific region of the ocean while `False Ocean` means the mission outcome was unsuccessfully landed to a specific region of the ocean. `True RTLS` means the mission outcome was successfully  landed to a ground pad `False RTL`S means the mission outcome was unsuccessfully landed to a ground pad. `True ASDS` means the mission outcome was successfully  landed to a drone ship `False ASDS` means the mission outcome was unsuccessfully landed to a drone ship. `None ASDS` and `None None` these represent a failure to land.

In [23]:
for i, outcome in enumerate(landing_outcomes.keys()):
    print(i, outcome)

0 True ASDS
1 None None
2 True RTLS
3 False ASDS
4 True Ocean
5 False Ocean
6 None ASDS
7 False RTLS

In [24]:
# set of outcomes where the second stage did not land successfully

false_outcomes = set(landing_outcomes.keys()[[1, 3, 5, 6, 7]])
false_outcomes

{'False ASDS', 'False Ocean', 'False RTLS', 'None ASDS', 'None None'}

In [27]:
landing_class = []
for i in df['Outcome']:
    if i in false_outcomes:
        landing_class.append(0)
    else:
        landing_class.append(1)

In [29]:
df['Class'] = landing_class
df[['Class']].head(10)

   Class
0      0
1      0
2      0
3      0
4      0
5      0
6      1
7      1
8      0
9      0

In [31]:
success_rate = df['Class'].mean()
success_rate.item()

0.6666666666666666