In [1]:
import folium
import pandas as pd

In [2]:
df=pd.read_csv('spacex_launch_geo.csv')
df.head()

,Flight Number,Date,Time (UTC),Booster Version,Launch Site,Payload,Payload Mass (kg),Orbit,Customer,Landing Outcome,class,Lat,Long
0,1,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0.0,LEO,SpaceX,Failure (parachute),0,28.562302,-80.577356
1,2,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel o...",0.0,LEO (ISS),NASA (COTS) NRO,Failure (parachute),0,28.562302,-80.577356
2,3,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2+,525.0,LEO (ISS),NASA (COTS),No attempt,0,28.562302,-80.577356
3,4,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500.0,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356
4,5,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677.0,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356

In [3]:
launch_map = folium.Map()
launch_sites = folium.map.FeatureGroup()

coordinates = df[['Launch Site', 'Lat', 'Long']].drop_duplicates()
coordinates

     Launch Site        Lat        Long
0    CCAFS LC-40  28.562302  -80.577356
26   VAFB SLC-4E  34.632834 -120.610745
36    KSC LC-39A  28.573255  -80.646895
49  CCAFS SLC-40  28.563197  -80.576820

In [4]:
for lat, lng, in zip(coordinates['Lat'], coordinates['Long']):
    launch_sites.add_child(
        folium.vector_layers.CircleMarker(
            [lat, lng],
            radius=5,
            color='yellow',
            fill=True,
            fill_color='blue',
            fill_opacity=0.6
        )
    )

latitudes = list(coordinates.Lat)
longitudes = list(coordinates.Long)
label = list(coordinates['Launch Site'])

latitudes, longitudes, label
#launch_map

([28.56230197, 34.63283416, 28.57325457, 28.56319718],
 [-80.57735648, -120.6107455, -80.64689529, -80.57682003],
 ['CCAFS LC-40', 'VAFB SLC-4E', 'KSC LC-39A', 'CCAFS SLC-40'])

In [6]:


for late, lon, lab in zip(latitudes, longitudes, label):
    folium.Marker([late, lon], popup=lab).add_to(launch_map)

launch_map.add_child(launch_sites)

launch_map